theme="github_dark"


[editor]
line-number = "relative"
scroll-lines = 1
# auto-pairs = false
mouse = true 
auto-format = true
bufferline="multiple"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
# hidden = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
# wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["version-control"]
right = [ "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
"S-ret" = ["move_line_up", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
X = "extend_line_above"
D = "delete_char_backward"
# y = ":clipboard-yank-join"
# Y = "yank_joined_to_clipboard"
# p = "paste_clipboard_before"
"H" = ":toggle lsp.display-inlay-hints"
# Move line up, down, right, left
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-h = ["delete_selection", "move_char_left", "paste_before"]
A-l = ["delete_selection", "move_char_right", "paste_after"] 

[keys.insert]
# j = { k = "normal_mode" } # Maps `jk` to exit insert mode
