[language-server.vscode-eslint-language-server.config]
format = { enable = true }
quiet = false

[language-server.vscode-eslint-language-server.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = true }

[language-server.vscode-eslint-language-server.config.codeActionOnSave]
enable = true
mode = "all"
source = { fixAll = { eslint = true } }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.ts", "--parser", "babel-ts"] }
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "typescript" ] }
auto-format = true
file-types = ["ts", "mts", "cts"]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.tsx"] }
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "tsx" ] }
auto-format = true
file-types = ["tsx", "mtsx", "ctsx"]

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
# formatter = { command = "prettier", args = [ "--parser", "babel-ts" ] }
formatter = { command = "prettier", args = ["--stdin-filepath", "file.js"] }
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "javascript" ] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
formatter = { command = "prettier", args = [ "--stdin-filepath", "file.jsx"] }
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "jsx" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "json" ] }
auto-format = true

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server" ]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server" ]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

# [[language]]
# name = "protobuf"
# auto-format = true

# [[grammar]]
# name = "protobuf"
# source = { git = "https://github.com/yusdacra/tree-sitter-protobuf", rev = "19c211a01434d9f03efff99f85e19f967591b175"}

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls" ]

